language: csharp
mono: none
dotnet: 2.2.109
script:
  - dotnet build ./GeneralAlgorithms/GeneralAlgorithms.csproj
  - dotnet build ./MapGeneration/MapGeneration.csproj
  - dotnet build ./GeneralAlgorithms.Tests/GeneralAlgorithms.Tests.csproj
  - dotnet build ./MapGeneration.Tests/MapGeneration.Tests.csproj
  - dotnet test ./GeneralAlgorithms.Tests/GeneralAlgorithms.Tests.csproj
  - dotnet test ./MapGeneration.Tests/MapGeneration.Tests.csproj